services:
  - type: web
    name: nonogram-admin
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: flask --app src.nonogram.admin.app run --host=0.0.0.0 --port=$PORT
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.14
      - key: PYTHONUNBUFFERED
        value: "1"
